version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-vollmed
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: api-rest-em-java
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env

volumes:
  mysql_data:

