name: CI/CD - Build, Testes e Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build do projeto com Maven
        run: mvn clean package -DskipTests=false

      - name: Executar testes
        run: mvn test

      - name: Gerar relatório de cobertura (JaCoCo)
        run: mvn jacoco:report

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t LuisAbranches/api-rest-java:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push LuisAbranches/api-rest-java:latest

