name: CI/CD - Build, Testes e Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: LuMy@45
          MYSQL_DATABASE: vollmed_api
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Esperar o MySQL iniciar
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL está pronto!"
              break
            fi
            echo "Aguardando MySQL..."
            sleep 2
          done
      - name: Cache do repositório Maven
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
              
      - name: Build do projeto com Maven
        run: mvn clean package -Dspring.profiles.active=test

      - name: Executar testes com perfil 'test'
        run: mvn test -Dspring.profiles.active=test

      - name: Gerar relatório de cobertura (JaCoCo)
        run: mvn clean verify -U --no-transfer-progress

      - name: Upload do relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-jacoco
          path: target/site/jacoco


      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t LuisAbranches/api-rest-java:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push LuisAbranches/api-rest-java:latest


